frontend/controllers/UserController.php
<?php
/**
 * Created by PhpStorm.
 * User: chvs
 * Date: 30.10.2017
 * Time: 1:20
 */

namespace frontend\controllers;

use frontend\models\Balance;
use frontend\models\Transfer;
use Yii;
use yii\web\Controller;
use common\models\Bills;
use common\models\Helpfunc;
use common\models\User;

class UserController extends Controller
{

  public function actionIndex()
  {
    return $this->render('index');
  }


  public function actionHistory()
  {

    $history = Bills::find()->where(['user_from' => Yii::$app->user->id])->orWhere(['user_to' => Yii::$app->user->id])->all();

//    Helpfunc::debug($history);
    $history[0]->emailuserto;
    $history[0]->emailuserfrom;

    $active_str = '';

    foreach ($history as $row) {
      if ($row['user_from'] == Yii::$app->user->id) $balance = $row['balance_from'];
      else $balance = $row['balance_to'];
      $active_str .= '<tr><td>' . $row['emailuserfrom'][0]['email'] . '</td><td>' . $row['emailuserto'][0]['email'] . '</td><td>' . $row['scope'] . '</td><td>' . $balance . '</td></tr>';
    }

    if ($active_str == '') {
      $active_str .= '<tr><td>n/a</td><td>n/a</td><td>n/a</td><td>n/a</td></tr>';
    }

    return $this->render('history', [
      'active_str' => $active_str,
    ]);

  }


  public function actionTransfer()
  {
    $model = new Transfer();

    if ($model->load(Yii::$app->request->post()) && $model->validate()) {

      User::transfer(
        $userFromId = Yii::$app->user->id,
        $userToEmail = $model->user_to,
        $scope = $model->scope,
        $model = $model
      );

    }

    return $this->render('transfer', compact("model"));
  }

}

frontend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */

/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;
use common\models\Helpfunc;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
  <meta charset="<?= Yii::$app->charset ?>">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <?= Html::csrfMetaTags() ?>
  <title><?= Html::encode($this->title) ?></title>
  <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
  <?php
  NavBar::begin([
    'brandLabel' => 'Test',
    'brandUrl' => Yii::$app->homeUrl,
    'options' => [
      'class' => 'navbar-inverse navbar-fixed-top',
    ],
  ]);
  $menuItems = [
    ['label' => 'Главная', 'url' => ['/site/index']],
  ];
  if (Yii::$app->user->identity) {
    $menuItems[] = ['label' => 'Личный кабинет', 'url' => ['/user/index']];
  }
  if (Yii::$app->user->isGuest) {
    $menuItems[] = ['label' => 'Зарегистрироваться', 'url' => ['/site/signup']];
    $menuItems[] = ['label' => 'Войти', 'url' => ['/site/login']];
  } else {
    $menuItems[] = '<li>'
      . Html::beginForm(['/site/logout'], 'post')
      . Html::submitButton(
        'Выйти (' . Yii::$app->user->identity->username . "  " . Helpfunc::r2f(Yii::$app->user->identity->getBalance()) . ' руб.)',
        ['class' => 'btn btn-link logout']
      )
      . Html::endForm()
      . '</li>';
  }
  echo Nav::widget([
    'options' => ['class' => 'navbar-nav navbar-right'],
    'items' => $menuItems,
  ]);
  NavBar::end();
  ?>

  <div class="container">
    <?= Breadcrumbs::widget([
      'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
    ]) ?>
    <?= Alert::widget() ?>
    <?= $content ?>
  </div>
</div>

<footer class="footer">
  <div class="container">
    <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

    <p class="pull-right"><?= Yii::powered() ?></p>
  </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>